ame: mlops

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ubuntu:20.04
    container: docker://dvcorg/cml-py3:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Adjust Python version if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "requirements.txt not found"; exit 1; fi
      - name: Train model
        run: |
          if [ -f expno5.py ]; then python expno5.py; else echo "expno5.py not found"; exit 1; fi
      - name: Generate report
        run: |
          echo "Model Metrics" > report.md
          if [ -f metrics.txt ]; then cat metrics.txt >> report.md; else echo "metrics.txt not found" >> report.md; fi
          echo "Model Performance" >> report.md
          echo "Model performance metrics are on the plot below." >> report.md
      - name: Publish model results
        run: |
          if [ -f model_results.png ]; then
            cml-publish model_results.png --md >> report.md
          else
            echo "model_results.png not found, skipping image publishing." >> report.md
          fi
      - name: Send report as comment
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml-send-comment report.md
