name: mlops
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Train model and generate report
        run: |
          python expno5.py
          echo "Model Metrics" > report.md
          cat metrics.txt >> report.md
          echo "Model Performance" >> report.md
          echo "Model performance metrics are on the plot below." >> report.md
          cml-publish model_results.png --md >> report.md

      - name: Post results as a comment
        run: |
          cat report.md | cml comment create --publish --target pr
