name: mlops
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ubuntu:22.04  # Ubuntu 22.04 includes GLIBC 2.35

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          apt update
          apt install -y nodejs npm python3 python3-pip git
          npm install -g @dvcorg/cml
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train my model
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python expno5.py

          echo "Model Metrics" > report.md
          cat metrics.txt >> report.md
          echo "Model Performance" >> report.md
          echo "Model performance metrics are on the plot below." >> report.md

          cml-publish model_results.png --md >> report.md
          cml-send-comment report.md
