name: mlops
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ubuntu:22.04  # Use a clean Ubuntu 22.04 container

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          apt update

          # Forcefully remove conflicting Node.js 12 and libnode-dev
          apt remove -y nodejs libnode-dev || true
          apt purge -y nodejs libnode-dev || true
          apt autoremove -y
          rm -rf /usr/include/node /usr/lib/node_modules /usr/bin/node || true

          # Install system dependencies
          apt install -y python3 python3-pip git curl npm

          # Install Node.js 18
          curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
          apt install -y nodejs

          # Verify installation
          node -v
          npm -v

          # Install CML
          npm install -g @dvcorg/cml

          # Ensure 'python' command works
          ln -s /usr/bin/python3 /usr/bin/python || true

          # Install Python dependencies
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train and Evaluate Model
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python expno5.py  # Run ML model

          # Generate Report
          echo "Model Metrics" > report.md
          cat metrics.txt >> report.md
          echo "Model Performance" >> report.md
          echo "Model performance metrics are shown in the plot below." >> report.md

          # Publish Results
          cml-publish model_results.png --md >> report.md
          cml-send-comment report.md
