name: mlops
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ubuntu:22.04  # Use a clean Ubuntu 22.04 container

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          set -e  # Exit immediately if a command fails
          
          echo "Updating package list..."
          apt update

          echo "Removing conflicting Node.js and libnode-dev packages..."
          dpkg --purge --force-all nodejs libnode-dev || true
          apt remove -y nodejs libnode-dev || true
          apt purge -y nodejs libnode-dev || true
          apt autoremove -y
          rm -rf /usr/include/node /usr/lib/node_modules /usr/bin/node || true

          echo "Installing required system dependencies..."
          apt install -y python3 python3-pip git curl npm

          echo "Installing Node.js 18..."
          curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
          apt install -y nodejs

          echo "Verifying Node.js installation..."
          node -v
          npm -v

          echo "Installing CML..."
          npm install -g @dvcorg/cml

          echo "Ensuring 'python' command works..."
          ln -s /usr/bin/python3 /usr/bin/python || true

          echo "Upgrading pip and installing Python dependencies..."
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train and Evaluate Model
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Running ML model..."
          python expno5.py  

          echo "Generating Report..."
          echo "Model Metrics" > report.md
          cat metrics.txt >> report.md
          echo "Model Performance" >> report.md
          echo "Model performance metrics are shown in the plot below." >> report.md

          echo "Publishing Results..."
          cml-publish model_results.png --md >> report.md
          cml-send-comment report.md
