name: mlops
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: 
      image: ubuntu:22.04  # Ensures GLIBC_2.28+
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        run: |
          apt update && apt install -y python3 python3-pip
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          python3 -m pip install -r requirements.txt
	  pip install cml  #  Ensure CML is installed here
          python3 expno5.py
          echo "Model Metrics" > report.md
          cat metrics.txt >> report.md
          echo "Model Performance" >> report.md
          echo "Model performance metrics are on the plot below." >> report.md
          
          cml-publish model_results.png --md >> report.md
          cml-send-comment report.md

