name: mlops
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ubuntu:20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Dependencies (Python, Pip, Node.js)
        run: |
          apt update
          apt install -y python3 python3-pip nodejs npm
          python3 -m pip install --upgrade pip

      - name: Install CML (via npm)
        run: |
          npm install -g @dvcorg/cml  # Correct way to install CML
          which cml || echo "CML not found!"

      - name: Train my model
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 -m pip install -r requirements.txt
          python3 expno5.py

          echo "Model Metrics" > report.md
          cat metrics.txt >> report.md
          echo "Model Performance" >> report.md
          echo "Model performance metrics are on the plot below." >> report.md

          # Ensure CML is installed before using it
          which cml-publish || echo "cml-publish not found!"
          cml-publish model_results.png --md >> report.md
          cml-send-comment report.md
