name: mlops
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest  # Pre-built with Python & Node.js

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          apt update && apt install -y git  # Ensure git is installed
          pip install --upgrade pip
          pip install -r requirements.txt  # Install Python dependencies
          npm install -g @dvcorg/cml       # Install CML via npm
          which cml || echo "CML not found!"

      - name: Train My Model
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python expno5.py  # Run model training script

          echo "Model Metrics" > report.md
          cat metrics.txt >> report.md
          echo "Model Performance" >> report.md
          echo "Model performance metrics are on the plot below." >> report.md

          cml-publish model_results.png --md >> report.md
          cml-send-comment report.md
